services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: .
    command: >
      sh -c "sleep 5 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn auth_service.wsgi:application --bind 0.0.0.0:8001"
    environment:
      DB_NAME: auth_db
      DB_USER: auth_user
      DB_PASSWORD: auth_password
      DB_HOST: auth-db
      DB_PORT: 5432
    depends_on:
      - auth-db

  recipes-service:
    image: recipes-service:latest
    expose:
      - "8000"

  meal-planner-service:
    image: meal-planner-service:latest
    expose:
      - "8002"

  gateway:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - recipes-service
      - meal-planner-service

volumes:
  auth_db_data: