events {}

http {
    upstream auth_service {
        server auth-service:8001;
    }

    upstream recipes_service {
        server recipes-service:8000;
    }

    upstream meal_planner_service {
        server meal-planner-service:8002;
    }

    server {
        listen 80;
        server_name localhost;

        client_max_body_size 10M;

        location /auth/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/recipes/ {
            proxy_pass http://recipes_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/meal-plans/ {
            proxy_pass http://meal_planner_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            return 200 'Foodgram gateway is running';
            add_header Content-Type text/plain;
        }
    }
}